version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: main
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: "@microsoft/api-documenter"
    versions:
    - 7.12.10
    - 7.12.11
    - 7.12.12
    - 7.12.13
    - 7.12.14
    - 7.12.15
    - 7.12.16
    - 7.12.17
    - 7.12.18
    - 7.12.19
    - 7.12.20
    - 7.12.21
    - 7.12.22
    - 7.13.0
    - 7.13.1
    - 7.13.2
    - 7.13.3
  - dependency-name: vite
    versions:
    - 2.1.0
    - 2.1.1
    - 2.1.2
    - 2.1.3
    - 2.1.4
    - 2.1.5
    - 2.2.0
    - 2.2.1
  - dependency-name: rollup
    versions:
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.1
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.0
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
    - 2.45.2
  - dependency-name: vue
    versions:
    - 3.0.10
    - 3.0.8
    - 3.0.9
  - dependency-name: "@vue/compiler-sfc"
    versions:
    - 3.0.10
    - 3.0.8
    - 3.0.9
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: ts-jest
    versions:
    - 26.5.3
    - 26.5.4
