name: DOCS

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build docs
        run: |
          cd site
          yarn install
          yarn build
          cd ..
          mv site/dist docs
          cp docs/index.html docs/404.html
          git config --global user.email actions@users.noreply.github.com
          git config --global user.name "Action"
          git add docs --force
          git commit -m"docs: update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'docs'
          force: true
